# Generated by Django 6.0.4 on 2026-04-25 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='order',
            field=models.PositiveIntegerField(default=999),
        ),
    ]
