# Generated by Django 6.0.5 on 2026-05-27 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Ime skupine')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('rooms', models.ManyToManyField(blank=True, related_name='groups', to='rooms.room', verbose_name='Prostori v skupini')),
            ],
            options={
                'verbose_name': 'Skupina prostorov',
                'verbose_name_plural': 'Skupine prostorov',
                'ordering': ['name'],
            },
        ),
    ]
