# Generated by Django 6.0.5 on 2026-05-27 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0007_parameter_format_decimals'),
        ('rooms', '0003_roomgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='Datum in čas dogodka')),
                ('title', models.CharField(max_length=200, verbose_name='Naziv dogodka')),
                ('description', models.TextField(blank=True, verbose_name='Opis / opomba')),
                ('color', models.CharField(default='#10b981', help_text='Barva črte na grafu (hex)', max_length=7, verbose_name='Barva')),
                ('parameters', models.ManyToManyField(blank=True, related_name='events', to='parameters.parameter', verbose_name='Parametri')),
                ('rooms', models.ManyToManyField(blank=True, related_name='events', to='rooms.room', verbose_name='Prostori')),
            ],
            options={
                'verbose_name': 'Dogodek',
                'verbose_name_plural': 'Dogodki',
                'ordering': ['-timestamp'],
            },
        ),
    ]
