services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: air_quality
      POSTGRES_USER: django
      POSTGRES_PASSWORD: geslo123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mqtt:
      image: eclipse-mosquitto:2
      restart: always
      ports:
        - "1883:1883"              # MQTT port
      volumes:
        - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"

  web:
    build: .
    command: uvicorn config.asgi:application --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
    entrypoint: ["sh", "-c", "python manage.py collectstatic --noinput && uvicorn config.asgi:application --host 0.0.0.0 --port 8000 --reload"]
      
  mqtt-listener:
    build: .
    command: python mqtt_listener.py
    depends_on:
      - db
      - redis
    restart: always
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
      
volumes:
  postgres_data: