# Generated by Django 6.0.3 on 2026-03-31 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parameters', '0001_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('floor', 'Tla'), ('ceiling', 'Strop'), ('wall', 'Stena'), ('table', 'Miza'), ('other', 'Drugo')], default='other', max_length=20)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='parameters.parameter')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='rooms.room')),
            ],
            options={
                'ordering': ['room', 'parameter'],
                'unique_together': {('room', 'parameter', 'location')},
            },
        ),
    ]
