# Generated by Django 6.0.3 on 2026-04-03 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0001_initial'),
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MqttSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(help_text='MQTT topic za poslušanje (npr. house/livingroom/co2)', max_length=255, unique=True)),
                ('qos', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2')], default=0)),
                ('parameter', models.ForeignKey(help_text='Kateri parameter ta topic predstavlja', on_delete=django.db.models.deletion.CASCADE, to='parameters.parameter')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mqtt_subscriptions', to='sensors.sensor')),
            ],
            options={
                'verbose_name': 'MQTT Subscription',
                'verbose_name_plural': 'MQTT Subscriptions',
                'unique_together': {('sensor', 'topic')},
            },
        ),
    ]
