# Generated by Django 6.0.3 on 2026-03-31 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0001_initial'),
        ('parameters', '0001_initial'),
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='measurement',
            constraint=models.UniqueConstraint(fields=('sensor', 'parameter', 'timestamp'), name='unique_measurement_per_sensor_parameter_time'),
        ),
    ]
