# Generated by Django 6.0.4 on 2026-04-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0002_auto_20260403_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='higher_is_worse',
            field=models.BooleanField(default=True, help_text='Označi, če višja vrednost parametra pomeni slabšo kakovost zraka (npr. CO2, AQI, PM2.5). Za temperaturo označi False.', verbose_name='Višja vrednost = slabše'),
        ),
    ]
