# Generated by Django 6.0.4 on 2026-04-24 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0003_parameter_higher_is_worse'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='order',
            field=models.PositiveIntegerField(default=999, help_text='Manjša številka = prikaže se višje na kompaktni kartici', verbose_name='Vrstni red na karticah'),
        ),
    ]
