# Generated by Django 6.0.5 on 2026-05-12 05:07

import datetime
from random import randrange
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0004_parameter_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='identifier',
            field=models.CharField(default=randrange(1000), max_length=50, unique=False),
            preserve_default=False,
        ),
    ]
