# Generated by Django 6.0.5 on 2026-05-12 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0005_parameter_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='identifier',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
