# Generated by Django 6.0.5 on 2026-05-24 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0006_alter_parameter_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='format_decimals',
            field=models.PositiveIntegerField(default=2, verbose_name='Number of decimal places on room cards etc.'),
        ),
    ]
